language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.45.0
    - rust: nightly
      script: |
          if rustup component add clippy-preview
          then
              cargo clippy --all -- -D warnings
          fi

script:
  - cargo build
  - cargo test
